name: floating
description: Picture in Picture mode management for Flutter. Available only for Android.
version: 1.1.0
homepage: https://gitlab.com/nicram606/floating

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0

flutter:
  plugin:
    platforms:
      android:
        package: eu.wroblewscy.marcin.floating.floating
        pluginClass: FloatingPlugin
